apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "eacp.labels" (dict "root" . "component" "serviceaccount") | nindent 4 }}
automountServiceAccountToken: false
